---
apiVersion: v1
kind: Service
metadata:
  name: kubevm-service
  namespace: kubevm-ns
spec:
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    app: kubevm
  sessionAffinity: None
  type: ClusterIP
